config/routes.rb
BuyMyBeer::Application.routes.draw do

  resources :projects do
    resources :builds, :only => [:create, :show]
  end

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#welcome'

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, :presence => true

  validates :users, :presence => true

  has_many :collaborations, :dependent => :destroy
  has_many :users, :through => :collaborations

  has_many :builds, :dependent => :destroy

  def initialize(attributes = nil, options = {})
    super(attributes, options)
    self[:uuid] = generate_uuid
  end

  private

  # Generate a UUID from the current time and a random number.
  # Assumes we don't have > 1,000,000 requests per second.
  def generate_uuid
    Digest::SHA2.hexdigest("#{Time.now.utc}--#{rand(1000000)}")
  end

end

app/controllers/projects_controller.rb
# This controller does not have ApplicationHelper methods??
class ProjectsController < ApplicationController

  before_filter :authenticate_user

  def index
    @projects = current_user.projects.includes(:users)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    @project.users << current_user

    if @project.save
      flash[:success] = 'Create project succeeded.'
      redirect_to root_path
    else
      flash[:failure] = "Create project failed: #{@project.errors.full_messages}."
      render :new, :layout => true
    end
  end

  def show
    begin
      @project = Project.includes(:builds => :last_commiter).find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:failure] = "Show project failed: #{e.message}."
      redirect_to root_path
    end
  end

  def destroy
    begin
      @project = Project.find(params[:id])
      if @project.destroy
        flash[:success] = "Delete project '#{@project.name}' succeeded."
      else
        flash[:failure] = "Delete project failed: #{@project.errors.full_messages}."
      end
    rescue ActiveRecord::RecordNotFound => e
      flash[:failure] = "Delete project failed: #{e.message}."
    end

    redirect_to root_path
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.haml
%tr.project
  %td.name= link_to(project.name, project_path(project.id))
  %td.collaborators= project.users.map{|u| u.email}
  %td.uuid= project.uuid
  %td.action= link_to('Delete', project_path(project.id), :method => :delete)

app/views/projects/index.html.haml
#projects

  %h2 Projects
  %h2.button= link_to('Create a New Project', new_project_path)

  -# TODO: Move this to a partial to avoid outputting the empty table.
  %table.projects{:border => '1'}
    %tr
      %th Name
      %th Collaborators
      %th URL
      %th Action
    = render @projects

  = 'You have no projects!' if @projects.empty?

app/views/projects/new.html.haml
%h1 New Project

= form_for @project do |f|
  .field
    = f.label      :name, 'Name'
    %br
    = f.text_field :name
  .action
    = f.submit 'Create'

app/views/projects/show.html.haml
%h2= "Project - #{@project.name}"

.name
  Name:
  = @project.name

.uuid
  UUID:
  = @project.uuid

.collaborators
  Collaborators:
  = @project.users.map{|u| u.email}

.builds
  %table.builds{:border => '1'}
    %tr
      %th Status
      %th Last Commit
      %th Last Committer
      %th Action
    = render :partial => 'builds/build', :collection => @project.builds

  = 'This project has no builds!' if @project.builds.empty?

app/views/projects/user_root.html.haml
%h1= @message

%h2= @current_user.email + ' is logged in!'